Task-outcomes card migration to Angular
doubtfire-lms/doubtfire-web pull request #299
Opened 2020-09-20 10:12 UTC by almuntasir

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x]  New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x]  My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x]  My changes generate no new warnings
- [x]  I have added tests that prove my fix is effective or that my feature works
- [x]  New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

If you have any questions, please contact @macite or @jakerenzella.
![task-outomes1](https://user-images.githubusercontent.com/65483284/93708922-7d4e7900-fb7d-11ea-9f02-7b268be30292.PNG)

2020-09-20 10:13 UTC, jakerenzella commented
Pull request description needs to be completed, please read the template for guidance and replace with the appropriate content.

2020-09-22 03:51 UTC, almuntasir commented
Hi Jake, 

I updated the pull request, please consider the task-outcomes-card and give me your feedback. Regards.

2020-09-29 02:10 UTC, jakerenzella requested changes

2020-09-29 02:10 UTC, jakerenzella commented on src/app/projects/states/dashboard/directives/task-dashboard/directives/task-outcomes-card/task-outcomes-card.component.html
> +          </p> -->
What is this commented block?

2020-09-29 02:10 UTC, jakerenzella commented on src/app/projects/states/dashboard/directives/task-dashboard/directives/task-outcomes-card/task-outcomes-card.component.ts
> +  //constructor(@Inject(outcomeService) private outcomes: any) {}
?

2020-09-29 02:10 UTC, jakerenzella commented on src/app/projects/states/dashboard/directives/task-dashboard/directives/task-outcomes-card/task-outcomes-card.component.ts
> +    let prevVal = JSON.stringify(change.previousValue);
What are we doing with these?

2020-09-29 02:10 UTC, jakerenzella commented on src/app/projects/states/dashboard/directives/task-dashboard/directives/task-submission-card/task-submission-card.tpl.html
> +      <tr ng-repeat="comment in task.comments">
this is not Angular

2020-11-11 06:07 UTC, closed without merging