Migrating Task-Status-Card FromAngularJS to Angular
doubtfire-lms/doubtfire-web pull request #302
Opened 2020-09-20 13:21 UTC by BaderAlotaibi

# Description

Converting The HTMl AngularJs to HTML Angular
and Converting the Coffee script to Typescript 
And do the needed changes to the related files.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X ] Bug fix (non-breaking change which fixes an issue)
 
# How Has This Been Tested?
run the server and there was no issue,
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings

If you have any questions, please contact @macite or @jakerenzella.

2020-09-20 14:56 UTC, BaderOtaibi commented
Hi Dr Jake 
Please accept my apologies, Mistakenly I want to comit the message as Task-Status-Selector
But I put 
Task-Status-Card 

So please consider the commit message for a Task-Status-Selector
As I am not able to do any change because I have submitted my pull request to the panel and also in my individual task. 
The problem is only in the message in the commit not in the code .

2020-09-29 02:08 UTC, jakerenzella commented
We don't want misleading commits in the history, please resubmit this PR with the correct commit name

2020-09-29 02:09 UTC, jakerenzella requested changes

2020-09-29 02:09 UTC, jakerenzella commented on src/app/tasks/task-status-selector/task-status-selector.component.html
> +
This still uses bootstrap styles and old icons, should be angular material mat-icon and styles

2020-09-29 03:37 UTC, BaderAlotaibi commented
> We don't want misleading commits in the history, please resubmit this PR with the correct commit name

For This request , It is Done 
for Converting the bootstrap , I will work on it now , and sorry for this as I have not thought about it

2020-09-29 03:54 UTC, BaderAlotaibi commented
![image](https://user-images.githubusercontent.com/68497676/94510871-320e2780-025b-11eb-8583-5f743d9be696.png)
This is a result of compiling the code after making the changes

2020-11-11 06:04 UTC, closed without merging

2020-11-11 06:04 UTC, jakerenzella commented
Not up to acceptable standards, misleading commit history and new warnings introduced.