feat(context): eslint fix to fix prefix error only 19 left of 56
doubtfire-lms/doubtfire-web pull request #390
Opened 2021-07-28 21:02 UTC by Roboromeo1

*Any italic text should be deleted from the final Pull Request text, including this line*

# Description

*Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.*

Fixes # (issue)

## Type of change

*Please delete options that are not relevant.*

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration*

## Testing Checklist:

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from @macite and @jakerenzella on the Pull Request

2021-07-28 23:52 UTC, macite requested changes
Please change strategy to solve issue - moving errors to warnings so that they are still raised and can be addressed.

2021-07-28 23:52 UTC, macite commented on .eslintrc.json
>            "error",
Lets not remove these "errors" all together. Instead, can we change them to "warn"? Then we can create a new PR to fix all of the warnings... followed by turning this back to errors 😄

2021-07-28 23:53 UTC, macite commented
Not sure I would call this a new "feature" PR. Quality or config is probably more accurate.

2021-07-29 00:40 UTC, jakerenzella commented
Further, it seems you have not built the project with the correct version of node, which has resulted in the large lock file. Please ensure Node v14 is used to build Angular projects such as Doubtfire

2021-07-29 00:41 UTC, jakerenzella commented
> Not sure I would call this a new "feature" PR. Quality or config is probably more accurate.

Also not sure why the context submessage has been used

2021-07-29 11:44 UTC, macite commented on .eslintrc.json
> +        //   {
Can we keep these details but switch to warn by updating the above "error" to "warn"?

2021-07-29 11:45 UTC, macite commented on .eslintrc.json
> +        //   "error",
Same here

2021-07-29 11:45 UTC, macite requested changes
Can you update to keep the existing settings but switch them to warn.

2021-07-30 04:26 UTC, macite approved these changes

2021-07-30 04:26 UTC, merged

2021-08-02 12:37 UTC, jakerenzella commented
@macite This shouldn't have been merged since it needed to be built with Node v14. This caused the Lock file to be bloated.

2021-08-03 00:47 UTC, macite commented
Sorry I didn't notice the lock file change 😞 @jakerenzella

2021-08-03 00:59 UTC, Roboromeo1 commented
@macite @jakerenzella sorry for the inconvenience caused I apologise got that. Should I change the node version to 14 and create a new Pr ? 😅

2021-08-03 01:05 UTC, jakerenzella commented
> @macite @jakerenzella sorry for the inconvenience caused I apologise got that. Should I change the node version to 14 and create a new Pr ? 😅

No worries at all it isn't well documented so not your fault. This is fine I'll look at this in another pr. Thanks for your contribution.

2021-08-03 01:20 UTC, Roboromeo1 commented
Thank you , I'll fix it asap and commit with my next pr 🙌

2021-08-03 01:52 UTC, jakerenzella commented
Actually what might help if you have some availability for this @Roboromeo1 is if you would be able to add some documentation to the web repo that Node v14 needs to be used when installing/updating packages for doubtfire-web!