Migrate/grade task modal
doubtfire-lms/doubtfire-web pull request #564
Opened 2022-07-21 23:51 UTC by leocomsci

# Description

Transfer PR started by @PerryRose 

This pull request migrates the grade-task-modal component from AngularJS to Angular.
The grade task modal component is opened from task-service.coffee using the grade task modal service, which receives a task object and passes it onto the component via a MatDialogRef. Depending on the task object, a student's submission can either be rated using a Mat Slider, or graded with a Mat Button Toggle Group, which uses the grade-icon component which I have migrated. Clicking the submit button calls the component's close function, which passes a rating and a grade value back to the service before then being passed back to task-service.coffee, which updates the task object on the backend.

## Quality Points Task
### Before:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/49971210/161677419-ccdba8ba-cfcc-4efd-a8f9-7cdc9bcf368b.png">

### After:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/49971210/167277852-9b7a66cc-24f7-4066-bfc1-6f3da08fb49a.png">

## Graded Task
### Before:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/49971210/163152445-ba72d736-e62b-401d-bef4-2b74bdd83d33.png">

### After:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/49971210/167821967-060779f2-d359-45f4-98ae-690bc2d2c0bd.png">

Fixes # (updates the old grade-task-modal component specified outlined in the migration task list)

## Type of change

_Please delete options that are not relevant._

- [x] Component migration

# How Has This Been Tested?

1. Log in as an admin
2. Go to Manage Units and choose a unit
4. Go to Tasks and choose a task
5. Go to Other Settings
6. To grade a task, tick the Graded option.
7. To rate a task, select a number for the Quality Points option
8. Save
9. Log in as a tutor
10. Go to Mark by Task Definition
11. Select a task
12. Select a submission and provide a rating

## Testing Checklist:

- [X] Tested in latest Chrome
- [X] Tested in latest Safari
- [X] Tested in latest Firefox

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have requested a review from _ and _ on the Pull Request

2022-08-09 00:18 UTC, leocomsci commented
@macite Hi Andrew, could you review this PR? I can't add you as a reviewer for this PR so I mentioned you in this comment.
I also change name of welcome component, Jake used WelcomeWizardComponent but there's just WelcomeComponent so I adjusted it. Also, there are some problems with karma module so I couldn't run unit tests.

2022-08-11 10:03 UTC, macite requested changes
This looks pretty close. Can you check these last few things and make adjustments or show that the implementation should be ok?

2022-08-11 10:03 UTC, macite commented on src/app/common/grade-icon/grade-icon.component.ts
> +  constructor(@Inject(gradeService) private GradeService: any) {}
There should be a new equivalent of this in typescript.

2022-08-11 10:03 UTC, macite commented on src/app/common/grade-icon/grade-icon.component.ts
> +  constructor(@Inject(gradeService) private GradeService: any) {}
Check if you can remove the GradeService from this and use the new code

2022-08-11 10:03 UTC, macite commented on src/app/groups/group-member-contribution-assigner/group-member-contribution-assigner.tpl.html
> +        <td>{{member.student_name}}</td>
this doesn't look right - with the new service we do not have any snake case properties

2022-08-11 10:03 UTC, macite commented on src/app/groups/group-member-contribution-assigner/group-member-contribution-assigner.tpl.html
> +        <td>{{member.student_name}}</td>
Check everything in this...

2022-08-11 10:03 UTC, macite commented on src/app/projects/states/portfolio/directives/portfolio-grade-select-step/portfolio-grade-select-step.tpl.html
> +            <grade-icon [grade]="grade"></grade-icon>
Can you check the muted state here... is this ok without it. It is not shown in the conversation.

2022-08-11 10:03 UTC, macite commented on src/app/units/states/portfolios/portfolios.tpl.html
>                  >All</span
How does this appear now when different grades are selected?

2022-08-11 10:03 UTC, macite commented on src/app/units/states/portfolios/portfolios.tpl.html
> -                class="text-{{$index == filterOptions.selectedGrade ? 'primary' : 'muted'}}"
As above

2024-11-04 09:16 UTC, merged