Looks/migrate home component
doubtfire-lms/doubtfire-web pull request #781
Opened 2023-12-11 21:49 UTC by BrianJCal99

# Description

Replaced FxLayout components with Tailwind equivalent while maintaining the visual appearance and responsiveness of the application. (welcome component)

## Before

![image](https://github.com/thoth-tech/doubtfire-web/assets/88503893/4403bc04-0d2e-4014-8aaf-21734401b281)

![image](https://github.com/thoth-tech/doubtfire-web/assets/88503893/4a3e0d36-8a85-40fa-a587-cb7884f19a31)

![image](https://github.com/thoth-tech/doubtfire-web/assets/88503893/d3696b14-d414-4403-86dc-496c7cb8f2b9)

## After

![image](https://github.com/thoth-tech/doubtfire-web/assets/88503893/7fb580f3-a718-4cd9-be2c-afc7feef0fd6)

![image](https://github.com/thoth-tech/doubtfire-web/assets/88503893/286e3f7b-2e23-4b6e-af13-6ce0fe0b00d1)

![image](https://github.com/thoth-tech/doubtfire-web/assets/88503893/ccbc518f-ee40-4691-ba11-802957c87dd6)

2023-12-11 21:49 UTC, BrianJCal99 commented
@maddernd

2023-12-21 04:46 UTC, jakerenzella commented
Looks like an OK start, but some issues:

`<span fxFlex="10"></span>` -> this should use tailwind's flex basis, although I'm not 100% sure what the equivalent unit would be. Could you look into that?

2023-12-21 04:47 UTC, jakerenzella requested changes

2023-12-21 04:47 UTC, jakerenzella commented on src/app/home/states/home/home.component.html
> +  <span style="flex-basis: 10%"></span>
This should use tailwind

2023-12-21 04:47 UTC, jakerenzella commented on src/app/home/states/home/home.component.html
> +  <span style="flex-basis: 10%"></span>
And here, the rest looks good!

2025-09-18 05:13 UTC, closed without merging