Feature/add jplag frontend
doubtfire-lms/doubtfire-web pull request #873
Opened 2024-09-20 11:49 UTC by JackSCarroll

Depends on [ doubtfire-lms/doubtfire-deploy#28 ](https://github.com/doubtfire-lms/doubtfire-deploy/pull/28)
Depends on [ doubtfire-lms/doubtfire-api#447 ](https://github.com/doubtfire-lms/doubtfire-api/pull/447)
Feasibility document: [ thoth-tech/documentation#528 ](https://github.com/thoth-tech/documentation/pull/528)
# Description

Added frontend UI to allow authorised users to download JPLAG reports for a task in a unit.
Button can be found in `task explorer` screen and clicking the three dots.
Using task filter allows you to download the report for each task.
![image](https://github.com/user-attachments/assets/bcf12328-4a8b-4695-8293-6aaf962d9655)

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

- After completing testing checklist in [ Feature/jplag  implementation447 ](https://github.com/doubtfire-lms/doubtfire-api/pull/447) you should be able to download the reports for each task you submitted files for.

## Testing Checklist:

- [X] Tested in latest Firefox

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] My changes generate no new warnings

2024-09-20 22:55 UTC, macite requested changes
How do JPLAG similarities appear when we switch into the similarity view?

2024-09-20 22:55 UTC, macite commented on src/app/common/footer/footer.component.html
> +        <button mat-menu-item (click)="downloadJPLAGReport()">
Hide this if there is no code similarity checks for the task definition

2024-09-20 22:55 UTC, macite commented on src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.component.html
> +        <button mat-menu-item (click)="downloadJPLAGReport()">
Hide this if the task def does not have code similarity checks

2025-07-14 11:51 UTC, b0ink commented
Merged into 10.0.x https://github.com/doubtfire-lms/doubtfire-web/pull/951

2025-07-14 11:51 UTC, closed without merging